# hostfs-posix-py on Hyperlight
#
# Unmodified Python stdlib (open/read/write/os.mkdir/os.stat) against a
# sandboxed host directory mounted at /host by lib/hostfs.

set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]
export DOCKER_BUILDKIT := "0"

kernel      := ".unikraft/build/hostfs-posix-py-hyperlight_hyperlight-x86_64"
initrd      := "hostfs-posix-py-initrd.cpio"
memory      := "96Mi"
image       := "hostfs-posix-py-hyperlight"
ghcr_kernel := "ghcr.io/danbugs/hyperlight-unikraft/hostfs-posix-py-kernel:latest"
mount_dir   := "./work"

[unix]
run:
    mkdir -p {{mount_dir}}
    hyperlight-unikraft {{kernel}} --initrd {{initrd}} --memory {{memory}} --mount {{mount_dir}} -- /hostfs_demo.py

[windows]
run:
    New-Item -ItemType Directory -Force -Path {{mount_dir}} | Out-Null
    hyperlight-unikraft {{kernel}} --initrd {{initrd}} --memory {{memory}} --mount {{mount_dir}} -- /hostfs_demo.py

[unix]
run-5:
    mkdir -p {{mount_dir}}
    hyperlight-unikraft {{kernel}} --initrd {{initrd}} --repeat 4 --memory {{memory}} --mount {{mount_dir}} -- /hostfs_demo.py

[windows]
run-5:
    New-Item -ItemType Directory -Force -Path {{mount_dir}} | Out-Null
    hyperlight-unikraft {{kernel}} --initrd {{initrd}} --repeat 4 --memory {{memory}} --mount {{mount_dir}} -- /hostfs_demo.py

rootfs:
    docker build --platform linux/amd64 --target cpio -t {{image}}-cpio .
    - docker rm -f {{image}}-tmp
    docker create --name {{image}}-tmp {{image}}-cpio /bin/true
    docker cp {{image}}-tmp:/output.cpio ./{{initrd}}
    docker rm -f {{image}}-tmp

[unix]
build:
    -kraft-hyperlight build --plat hyperlight --arch x86_64

[windows]
build:
    docker pull {{ghcr_kernel}}
    - docker rm -f {{image}}-kernel-tmp
    docker create --name {{image}}-kernel-tmp {{ghcr_kernel}} /kernel
    New-Item -ItemType Directory -Force -Path (Split-Path {{kernel}}) | Out-Null
    docker cp {{image}}-kernel-tmp:/kernel ./{{kernel}}
    docker rm -f {{image}}-kernel-tmp

[unix]
clean:
    rm -rf .unikraft {{initrd}}

[windows]
clean:
    if (Test-Path .unikraft) { Remove-Item -Recurse -Force .unikraft }
    if (Test-Path {{initrd}}) { Remove-Item -Force {{initrd}} }
